# Site
repository: ibrahimjassat/cv
favicon: images/profile_picture.jpeg

# Content configuration version
version: 2

# Personal info
name: Ibrahim Jassat
title: Senior Test Engineer / Senior Software Developer in Test
email: jassat.ibrahim@gmail.com
#website: www.github.com/ibrahimjassat

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  IbrahimJassat
linkedin_username: IbrahimJassat

# About Section
# about_title: About Me
about_profile_image: images/profile_picture.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ibrahim and I'm a Senior Developer in Test. 
  A Dedicated QA Engineer with a proven 
  track record in ensuring unparalleled customer satisfaction through meticulous analysis, innovative 
  test automation strategies, and seamless defect management. Proficient in developing and implementing 
  robust test automation frameworks and performance testing solutions, optimizing product functionality 
  while adhering to stringent deadlines.
content:
  - title: Key Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description: | # this will include new lines to allow paragraphs
          - Strategic Testing & Defect Management - Proficient in analyzing user requirements, crafting user scenarios, and adeptly managing defects using Jira, ensuring optimal user satisfaction and product quality.
          - Advanced Test Automation Expertise - Skilled in leading comprehensive automated test coverage using Java Selenium, REST API, Gatling, and JMeter, enhancing functionality and performance while maintaining high user satisfaction.
          - Framework Development - Experienced in building Test Automation frameworks from scratch utilizing Playwright, TypeScript, and Java, alongside constructing Performance Testing frameworks in Scala, improving testing efficiency and code reusability.
          - Agile Collaboration & Process Enhancement - Collaborative Agile practitioner adept at maintaining an Agile focus within multi-disciplinary teams, driving biweekly sprint goals, advising on process improvements, and facilitating standardized testing processes for enhanced functionality.
          - Proactive Issue Resolution & Release Management - Demonstrated ability in delivering real-time hotfixes, mitigating risks with release candidates, and coordinating fixes to developer environments, ensuring seamless team collaboration and alignment with business objectives.
          - With a solid foundation in Agile methodologies, a knack for innovative problem-solving, and a commitment to continuous improvement, I am poised to drive excellence in quality assurance, elevating products to new standards of excellence.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Senior Software Developer in Test
        sub_title: Driver and Vehicle Standard Agency (DVSA), Nottingham, UK
        caption: November 2023 - Present
        description: | # this will include new lines to allow paragraphs
           PENDING 

  - layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Test Engineer 
        sub_title: Driver and Vehicle Standard Agency (DVSA), Nottingham, UK
        caption: October 2017 - October 2023
        description: | # this will include new lines to allow paragraphs
           - Analysing user requirements to ensure customer and user satisfaction are met through the creation of user scenarios and reporting and managing defects when they arise in Jira.
           - Leading comprehensive automated test coverage in Java Selenium and REST API.
           - Testing and implementing new functionality, ensuring high customer and user satisfaction and improving performance bottlenecks - using Gatling and JMeter.
           - Building Test Automation frameworks from scratch using Playwright and Typescript using languages such as Typescript and Java.
           - Building Performance Testing frameworks in Scala.
           - Designing and implementing robust test automation processes across in CI/CD deployment along with sub system integrations.
           - Delivering hotfixes in real-time after reviewing critical customer issues on demand.
           - Maintained an Agile focus in collaboration with multi-disciplinary Agile teams in line with biweekly sprint goals.       
           - Advised on processes & strategies to propose change coverage for improved functionality and standardised testing processes.

      - layout: centre
        description: | # this will include new lines to allow paragraphs
            Key Achievements
            
            - Local Recognition Award from the Principal Developer in 2023 in recognition for Operational Excellence for identifying irregularities and potential cyber security issue on Roadside Payment Application.
            
            - Local Recognition Award from the Head of Delivery Management in 2022 in recognition for an Achievement & Delivery of outstanding & successful delivery of Delivery of AWS Cognito authentication service for the MOT Application.
            
            - Local Recognition Award from the Head of Delivery Management in 2022 in recognition for an Achievement & Delivery of outstanding & successful delivery of MOT History. 
            
            - Local Recognition Award from the Director of Strategy, Policy and Digital in 2020.
            
            - Local Recognition Award from the Director of Digital Services and Technology in 2019.
            
            - Written an article in the annual review 2018/2019 at the DVSA.
            
            - Part of the team which won the UK Civil Servant award for Digital project of the year 2018. 
            
            - Successfully developed an automation pack showcasing a positive impact on cost & time.
            
            - Brilliant Civil service award for improved outcomes for Emergency Driving Test Application Service Team.     

  - layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Digital Service Graduate - Tech
        sub_title: Driver and Vehicle Standard Agency (DVSA), Nottingham, UK
        caption: January 2017 - October 2017
        description: | # this will include new lines to allow paragraphs
            - Illustrated the application architecture to stakeholders and other technical communities in a comprehendible manner.
            - Investigated daily various solutions for new functionality which was being delivered.
            - Ensuring features and functionality was of a high standard for product owners.
            - Confidently improvised testing techniques to ensure efficient and effective testing was carried out, whilst remaining calm and working to strict deadlines.    
            - Presenting solutions with an agile mindset to test and change coverage for new and current feature/functionality.         
            - Developing code at high coding standards to improve reusability of functions for wider efficiency.          
            - Co-ordinated fixes to developer environments to contribute to the wider team and meet business objectives.         
            - Actively decreased the risk of issues with release candidates by collaborating and working to a high standard across teams.

      - layout: centre
        description: | # this will include new lines to allow paragraphs
            Key Achievements
            
            - Created and presented a system architecture diagram of the project which was used to help stakeholders to understand how the application works - which is still being used today.     

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: MOT Transformation project
        link: github.com/dvsa
        # link_text: Project Website
        additional_links:
          - title:  github.com/dvsa
            icon: fab fa-github
            url: github.com/dvsa
        description: | # this will include new lines to allow paragraphs
          As a Software Developer in Test on the MOT Transformation Project, I was responsible for ensuring the quality and reliability of newly modernized services 
          within a microservices and cloud-native architecture. I developed robust automated test suites for APIs and UI components using tools like Selenium, Postman, 
          and Jest, integrated into CI/CD pipelines via GitHub Actions. I implemented test strategies for performance, 
          and regression testing, and used tools like JMeter and OWASP ZAP. Working in Agile sprints, I collaborated closely with developers and product owners, 
          contributing to test coverage, defect prevention
      - layout: top-middle
        title: Common Payment Management System (CPMS)
        # link: github.com/dvsa
        # # link_text: Project Website
        # additional_links:
        #   - title:  github.com/dvsa
        #     icon: fab fa-github
        #     url: github.com/dvsa
        # description: | # this will include new lines to allow paragraphs
        #   As a Software Developer in Test on the MOT Transformation Project, I was responsible for ensuring the quality and reliability of newly modernized services 
        #   within a microservices and cloud-native architecture. I developed robust automated test suites for APIs and UI components using tools like Selenium, Postman, 
        #   and Jest, integrated into CI/CD pipelines via GitHub Actions. I implemented test strategies for performance, 
        #   and regression testing, and used tools like JMeter and OWASP ZAP. Working in Agile sprints, I collaborated closely with developers and product owners, 
        #   contributing to test coverage, defect prevention
      - layout: top-middle
        title: Roadside Payments (RSP)
        # link: github.com/dvsa
        # # link_text: Project Website
        # additional_links:
        #   - title:  github.com/dvsa
        #     icon: fab fa-github
        #     url: github.com/dvsa
        # description: | # this will include new lines to allow paragraphs
        #   As a Software Developer in Test on the MOT Transformation Project, I was responsible for ensuring the quality and reliability of newly modernized services 
        #   within a microservices and cloud-native architecture. I developed robust automated test suites for APIs and UI components using tools like Selenium, Postman, 
        #   and Jest, integrated into CI/CD pipelines via GitHub Actions. I implemented test strategies for performance, 
        #   and regression testing, and used tools like JMeter and OWASP ZAP. Working in Agile sprints, I collaborated closely with developers and product owners, 
        #   contributing to test coverage, defect prevention
      - layout: top-middle
        title: Heavy Vehicle Testing (HVT)
        link: github.com/dvsa
        # link_text: Project Website
        additional_links:
          - title:  github.com/dvsa
            icon: fab fa-github
            url: github.com/dvsa
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          As a Software Developer in Test on the DVSA Heavy Vehicle Testing (HVT) Project, 
          I was responsible for ensuring the quality and stability of digital services supporting heavy vehicle inspections. 
          I developed and maintained automated test suites using Playwright for end-to-end testing, fully integrated into CI/CD pipelines. 
          Working closely with Developers, DevOps engineers, and Business Analysts in Agile sprints, I helped improve deployment reliability and 
          streamline test environments. I implemented comprehensive test strategies covering functional, regression, and accessibility testing, 
          supported UAT and contributed to enhancing automation efficiency, software quality, and overall release confidence across the project.         - layout: top-middle
      - layout: top-middle
        title: Emergency Driving Tests 
        # link: github.com/dvsa
        # # link_text: Project Website
        # additional_links:
        #   - title:  github.com/dvsa
        #     icon: fab fa-github
        #     url: github.com/dvsa
        # description: | # this will include new lines to allow paragraphs
        #   As a Software Developer in Test on the MOT Transformation Project, I was responsible for ensuring the quality and reliability of newly modernized services 
        #   within a microservices and cloud-native architecture. I developed robust automated test suites for APIs and UI components using tools like Selenium, Postman, 
        #   and Jest, integrated into CI/CD pipelines via GitHub Actions. I implemented test strategies for performance, 
        #   and regression testing, and used tools like JMeter and OWASP ZAP. Working in Agile sprints, I collaborated closely with developers and product owners, 
        #   contributing to test coverage, defect prevention

  - title: Qualifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - ISTQB Certified Tester Foundation Level 2018
      - MSc Computing, De Montfort University, UK 
      - BSc Computer Science (Hons), De Montfort University, UK    

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Football
      - Gaming
      - Formula 1
      - Lego

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
